<?php

class OptionRecord{

	public function getSex(){
		return array(
		'Male',
		'Female',
		);
	}
	
	public function getClassifications(){
		return array(
		'Goods',
		'Infrastructure',
		'Consulting Services',
		);
	}
	
	public function getCategories(){
		return array(
		"don't use this",
		);
	}
	
	public function getOrganizationForms(){
		return array(
		'Single Proprietorship',
		'Partnership',
		'Corporation',
		'Cooperative',
		'Individual Local Consultant',
		);
	}
	
	public function getOrganizationTypes(){
		return array(
		'Distributor',
		'Exclusive / Sole Distributor',
		'General Merchandise',
		'Information Technology',
		'Manufacturer',
		'Non-Government Organizations',
		'Others',
		'Services',
		'System Integrator',
		'Telecommunications Solutions Provider',
		'Trading',
		'Consultancy',
		'General Contractor',
		);
	}
	
	public function getBusinessCategories(){
		return array(
	 'Advertising Agency Services',
	 'Agricultural Chemicals',
	 'Agricultural Machinery and Equipment',
	 "Agricultural Products (Seeds, Seedlings, Plants..)",
	 'Airconditioning and Airconditioning Systems',
	 'Airconditioning Maintenance Services',
	 'Aircraft Spare Parts',
	 'Ammunitions and Explosives',
	 'Animal Feeds',
	 'Appliances',
	 'Architectural Design',
	 'Arts and Crafts Accessories and Supplies',
	 'Audio and Visual Equipment',
	 'Automation Equipment',
	 'Aviation Products',
	 'Aviation Services',
	 'Bedclothes, Linens and Towels',
	 'Books, Maps and Other Publications',
	 'CAD Services',
	 'Cargo Forwarding and Hauling Services',
	 'Catering Services',
	 'Chemicals and Chemical Products',
	 'Communication Equipment',
	 'Communication Equipment, Parts and Accessories',
	 'Computer Furniture',
	 'Construction Equipment',
	 'Construction Management Services',
	 'Construction Materials and Supplies',
	 'Construction Projects',
	 'Consulting Services',
	 'Corporate Giveaways',
	 'Dairy Products',
	 'Diagnostic and Laboratory Services',
	 'Drugs and Medicines',
	 'Educational Materials and Supplies',
	 'Electrical Supplies',
	 'Electrical Systems and Lighting Components',
	 'Electronic Parts and Components',
	 'Engineering and Laboratory Testing Equipment',
	 'Environmental Health/Safety Equipment',
	 'Events Management',
	 'Fertilizers',
	 'Fire Fighting, Rescue and Safety Equipment',
	 'Fixtures',
	 'Flags',
	 'Food Processing Equipment',
	 'Food Stuff',
	 'Fuels/Fuel Additives & Lubricants & Anti Corrosive',
	 'Furniture',
	 'Furniture Parts and Accessories',
	 'Games and Toys',
	 'Gaming Equipment and Paraphernalia',
	 'Garments',
	 'General Contractor',
	 'General Engineering Services',
	 'General Merchandise',
	 'General Repair and Maintenance Services',
	 'Geotechnical Instrumentation',
	 'Grocery Items',
	 'Guns and Weapons',
	 'Hardware and Construction Supplies',
	 'Helicopters - Parts',
	 'Horizontal Directional Drilling',
	 'Hospital / Medical Equipment',
	 'Hospital / Medical Equipment Services',
	 'Hotel and Lodging and Meeting Facilities',
	 'Hydrological Instruments',
	 'Industrial Machinery and Equipment',
	 'Industrial pumps and compressors',
	 'Industrial Safety Equipment',
	 'Information Technology',
	 'Information Technology Parts, Accessories & Periph',
	 'Internet Services',
	 'Investigative Equipment',
	 'Janitorial Equipment',
	 'Janitorial Services',
	 'Janitorial Supplies',
	 'Kitchenware',
	 'Laboratory Supplies and Equipment',
	 'Lease and Rental of Property or Building',
	 'Lifting equipment and accessories',
	 'Live Animals (Livestock, Birds, Live fish & etc..)',
	 'Machine Tools',
	 'Mail and Cargo Transport Services',
	 'Mailing Supplies',
	 'Marine Transport',
	 'Maritime Spare Parts',
	 'Market Research Services',
	 'Medical and Dental Equipment',
	 'Medical Supplies and Laboratory Instrument',
	 'Metal Fabrication',
	 'Meteorological Equipments and Instruments',
	 'Microfilm Equipment',
	 'Microfilm Equipment - Supplies and Accesories',
	 'Mining Equipment and Supplies',
	 'Musical Instrument Parts and Accesories',
	 'Musical Instruments',
	 'Navigation Equipment',
	 'Newspapers',
	 'Office Equipment',
	 'Office Equipment Parts and Accessories',
	 'Office Equipment Supplies and Consumables',
	 'Office Supplies and Devices',
	 'Oil/Heat Chemical Resistant Rubber',
	 'Ordnance Products',
	 'Packaging Supplies and Materials',
	 'Personal Care Products',
	 'Pest Control Products',
	 'Pest Control Services',
	 'Photographic Equipment',
	 'Photographic Parts, Supplies and Accessories',
	 'Plastic Products',
	 'Power Generating Sets',
	 'Preserved or Processed Foods',
	 'Print and Broadcast and Aerial Advertising',
	 'Printing Services',
	 'Printing Supplies',
	 'Public Relations Programs or Services',
	 'Purses, handbags and bags',
	 'Quartermaster Items',
	 'Radiological/Diagnostic Equipment',
	 'Reproduction Services',
	 'Rice Milling Services',
	 'Safety and Occupational Products',
	 'Sale of Property or Building',
	 'Security Services',
	 'Security Surveillance and Detection Equipment',
	 'Services',
	 'Signage and Accessories',
	 'Sporting Goods',
	 'Structured Cabling',
	 'Sub-station Contractors',
	 'Surveying Instruments',
	 'Surveying Services',
	 'Systems Integration',
	 'Telecommunications Engineering',
	 'Telecommunications Provider',
	 'Textiles',
	 'Tokens and Awards',
	 'Traffic Control Systems',
	 'Transmission and Distribution Lines',
	 'Transportation and Communications Services',
	 'Travel, Food, Lodging and Entertainment Services',
	 'Vehicle Parts and Accessories',
	 'Vehicle Repair and Maintenance',
	 'Vehicles',
	 'Veterinary Products and Supplies',
	 'Video Production Services',
	 'Water and Waste Water Treatment Supply & Disposal',
	 'Water Service Connection Materials/Fittings',
	 'Well Drilling and Construction Services',
				);
	}
	
	public function getCountries(){
		return array(
		);
	}
	
	public function getRegions(){
		return array(
		'ARMM',
		'CAR',
		'Caraga',
		'NCR',
		'Region I',
		'Region II',
		'Region III',
		'Region IV-A',
		'Region IV-B',
		'Region V',
		'Region VI',
		'Region VII',
		'Region VIII',
		'Region IX',
		'Region X',
		'Region XI',
		'Region XII',
		);	
	}
		
	public function getProvinces(){
		return array(
		'Basilan',
		'Lanao Del Sur',
		'Maguindanao',
		'Sulu',
		'Tawi-Tawi',
		'Abra',
		'Apayao',
		'Benguet',
		'Ifugao',
		'Kalinga',
		'Mountain Province',
		'Agusan Del Norte',
		'Agusan Del Sur',
		'Dinagat Island',
		'Surigao Del Norte',
		'Surigao Del Sur',
		'Metro Manila',
		'Ilocos Norte',
		'Ilocos Sur',
		'La Union',
		'Pangasinan',
		'Batanes',
		'Cagayan',
		'Isabela',
		'Nueva Vizcaya',
		'Quirino',
		'Aurora',
		'Bataan',
		'Bulacan',
		'Nueva Ecija',
		'Pampanga',
		'Tarlac',
		'Zambales',
	 	'Batangas',
		'Cavite',
		'Laguna',
		'Quezon',
		'Rizal',
		'Marinduque',
		'Occidental Mindoro',
		'Oriental Mindoro',
		'Palawan',
		'Romblon',
		'Basilan',
		'Zamboanga Del Norte',
		'Zamboanga Del Sur',
		'Zamboanga Sibugay',
		'Albay',
		'Camarines Norte',
		'Camarines Sur',
		'Catanduanes',
		'Masbate',
		'Sorsogon',
		'Aklan',
		'Antique',
		'Capiz',
		'Guimaras',
		'Iloilo',
		'Negros Occidental',
		'Bohol',
		'Cebu',
		'Negros Oriental',
		'Siquijor',
		'Biliran',
		'Eastern Samar',
		'Leyte',
		'Northern Samar',
		'Samar',
		'Southern Leyte',
		'Bukidnon',
		'Camiguin',
		'Lanao Del Norte',
		'Misamis Occidental',
		'Misamis Oriental',
		'Compostela Valley',
		'Davao Del Norte',
		'Davao Del Sur',
		'Davao Oriental',
		'Cotabato',
		'Sarangani',
		'South Cotabato',
		'Sultan Kudarat'
		);	
	}
	
	public function getCitiesorMunicipalities(){
		return array(
			'Baay-Licuan',
'Bangued',
'Boliney',
'Bucay',
'Bucloc',
'Daguioman',
'Danglas',
'Dolores',
'La Paz',
'Lacub',
'Lagangilang',
'Lagayan',
'Langiden',
'Luba',
'Malibcong',
'Manabo',
'Peñarrubia',
'Pidigan',
'Pilar',
'Sallapadan',
'San Isidro',
'San Juan',
'San Quintin',
'Tayum',
'Tineg',
'Tubo',
'Villaviciosa',
 'Buenavista',
'Butuan City',
'Cabadbaran',
'Carmen',
'Jabonga',
'Kitcharao',
'Las Nieves',
'Magallanes',
'Nasipit',
'R.T. Romuladez',
'Santiago',
'Tubay',
 'Bayugan',
'Bunawan',
'Esperanza',
'La Paz',
'Loreto',
'Prosperidad',
'Rosario',
'San Francisco',
'San Luis',
'Sibagat',
'Sta. Josefa',
'Talacogon',
'Trento',
'Veruela',
 'Altavas',
'Balete',
'Banga',
'Batan',
'Buruanga',
'Ibajay',
'Kalibo',
'Lezo',
'Libacao',
'Madalag',
'Makato',
'Malay',
'Malinao',
'Nabas',
'New Washington',
'Numancia',
'Tangalan',
 'Bacacay',
'Camalig',
'Daraga',
'Guinobatan',
'Jovellar',
'Legazpi City',
'Libon',
'Ligao City',
'Malilipot',
'Malinao',
'Manito',
'Oas',
'Pio Duran',
'Polangui',
'Rapu-Rapu',
'Sto. Domingo',
'Tabaco City',
'Tiwi',
 'Anini-Y',
'Barbaza',
'Belison',
'Bugasong',
'Caluya',
'Culasi',
'Hamtic',
'Laua-an',
'Libertad',
'Pandan',
'Patnongon',
'San Jose',
'San Remigio',
'Sebaste',
'Sibalom',
'Tibiao',
'Tobias Fornier',
'Valderrama',
 'Calanasan',
'Conner',
'Flora',
'Kabugao',
'Luna',
'Pudtol',
'Sta. Marcela',
 'Baler',
'Casiguran',
'Dilasag',
'Dinalungan',
'Dingalan',
'Dipaculao',
'Maria Aurora',
'San Luis',
 'Isabela City',
'Lamitan',
'Lantawan',
'Maluso',
'Sumisip',
'Tipo-tipo',
'Tuburan',
 'Abucay',
'Bagac',
'Balanga City',
'Dinalupihan',
'Hermosa',
'Limay',
'Mariveles',
'Morong',
'Orani',
'Orion',
'Pilar',
'Samal',
 'Basco',
'Itbayat',
'Ivana',
'Mahatao',
'Sabtang',
'Uyugan',
 'Agoncillo',
'Alitagtag',
'Balayan',
'Balete',
'Batangas City',
'Bauan',
'Calaca',
'Calatagan',
'Cuenca',
'Ibaan',
'Laurel',
'Lemery',
'Lian',
'Lipa City',
'Lobo',
'Mabini',
'Malvar',
'Mataas Na Kahoy',
'Nasugbu',
'Padre  Garcia',
'Rosario',
'San Jose',
'San Juan',
'San Luis',
'San Nicolas',
'San Pascual',
'Sta. Teresita',
'Sto. Tomas',
'Taal',
'Talisay',
'Tanauan City',
'Taysan',
'Tingloy',
'Tuy',
 'Atok',
'Baguio City',
'Bakun',
'Bokod',
'Buguias',
'Itogon',
'Kabayan',
'Kapangan',
'Kibungan',
'La Trinidad',
'Mankayan',
'Sablan',
'Tuba',
'Tublay',
 'Almeria',
'Biliran',
'Cabucgayan',
'Caibiran',
'Culaba',
'Kawayan',
'Maripipi',
'Naval',
 'Albuquerque',
'Alicia',
'Anda',
'Antequera',
'Baclayon',
'Balilihan',
'Batuan',
'Bien Unido',
'Bilar',
'Buenavista',
'Calape',
'Candijay',
'Carmen',
'Catigbian',
'Clarin',
'Corella',
'Cortes',
'Dagohoy',
'Danao',
'Dauis',
'Dimiao',
'Duero',
'Garcia Hernandez',
'Guindulman',
'Inabanga',
'Jagna',
'Jetafe',
'Lila',
'Loay',
'Loboc',
'Loon',
'Mabini',
'Maribojoc',
'Panglao',
'Pilar',
'Pres. Carlos P. Garcia',
'Sagbayan',
'San Isidro',
'San Miguel',
'Sevilla',
'Sierra Bullones',
'Sikatuna',
'Tagbilaran City',
'Talibon',
'Trinidad',
'Tubigon',
'Ubay',
'Valencia',
 'Baungon',
'Cabanglasan',
'Damulog',
'Dangcagan',
'Don Carlos',
'Impasug-ong',
'Kadingilan',
'Kalilangan',
'Kibawe',
'Kitaotao',
'Lantapan',
'Libona',
'Malaybalay City',
'Malitbog',
'Manolo Fortich',
'Maramag',
'Pangantucan',
'Quezon',
'San Fernando',
'Sumilao',
'Talakag',
'Valencia City',
 'Angat',
'Balagtas',
'Baliuag',
'Bocaue',
'Bulacan',
'Bustos',
'Calumpit',
'Doña Remedios Trinidad',
'Guiguinto',
'Hagonoy',
'Malolos City',
'Marilao',
'Meycauayan City',
'Norzagaray',
'Obando',
'Pandi',
'Paombong',
'Plaridel',
'Pulilan',
'San Ildefonso',
'San Jose Del Monte City',
'San Miguel',
'San Rafael',
'Sta. Maria',
 'Abulug',
'Alcala',
'Allacapan',
'Amulung',
'Aparri',
'Baggao',
'Ballesteros',
'Buguey',
'Calayan',
'Camalaniugan',
'Claveria',
'Enrile',
'Gattaran',
'Gonzaga',
'Iguig',
'Lal-Lo',
'Lasam',
'Pamplona',
'Peñablanca',
'Piat',
'Rizal',
'Sanchez-Mira',
'Solana',
'Sta. Ana',
'Sta. Praxedes',
'Sta. Teresita',
'Sto. Niño (Faire)',
'Tuao',
'Tuguegarao City',
 'Basud',
'Capalonga',
'Daet',
'Jose Panganiban',
'Labo',
'Mercedes',
'Paracale',
'San Lorenzo Ruiz',
'San Vicente',
'Santa Elena',
'Talisay',
'Vinzons',
 'Baao',
'Balatan',
'Bato',
'Bombon',
'Buhi',
'Bula',
'Cabusao',
'Calabanga',
'Camaligan',
'Canaman',
'Caramoan',
'Del Gallego',
'Gainza',
'Garchitorena',
'Goa',
'Iriga City',
'Lagonoy',
'Libmanan',
'Lupi',
'Magarao',
'Milaor',
'Minalabac',
'Nabua',
'Naga City',
'Ocampo',
'Pamplona',
'Pasacao',
'Pili',
'Presentacion',
'Ragay',
'Sagñay',
'San Fernando',
'San Jose',
'Sipocot',
'Siruma',
'Tigaon',
'Tinambac',
 'Catarman',
'Guinsiliban',
'Mahinog',
'Mambajao',
'Sagay',
 'Cuartero',
'Dao',
'Dumalag',
'Dumarao',
'Ivisan',
'Jamindan',
'Maayon',
'Mambusao',
'Panay',
'Panit-An',
'Pilar',
'Pontevedra',
'President Roxas',
'Roxas City',
'Sapi-An',
'Sigma',
'Tapaz',
 'Bagamanoc',
'Baras',
'Bato',
'Caramoran',
'Gigmoto',
'Pandan',
'Panganiban',
'San Andres',
'San Miguel',
'Viga',
'Virac',
 'Alfonso',
'Amadeo',
'Bacoor',
'Carmona',
'Cavite City',
'Dasmariñas City',
'Gen. E. Aguinaldo',
'Gen. Mariano Alvarez',
'Gen. Trias',
'Imus',
'Indang',
'Kawit',
'Magallanes',
'Maragondon',
'Mendez-Nuñez',
'Naic',
'Noveleta',
'Rosario',
'Silang',
'Tagaytay City',
'Tanza',
'Ternate',
'Trece Martirez City',
 'Alcantara',
'Alcoy',
'Alegria',
'Aloguinsan',
'Argao',
'Asturias',
'Badian',
'Balamban',
'Bantayan',
'Barili',
'Bogo',
'Boljoon',
'Borbon',
'Carcar',
'Carmen',
'Catmon',
'Cebu City',
'Compostela',
'Consolacion',
'Cordova',
'Daan Bantayan',
'Dalaguete',
'Damanjug',
'Danao City',
'Ginatilan',
'Lapu-Lapu City',
'Liloan',
'Madridejos',
'Malabuyoc',
'Mandaue City',
'Medellin',
'Minglanilla',
'Moalboal',
'Naga',
'Oslob',
'Pilar',
'Pinamungajan',
'Poro',
'Ronda',
'Samboan',
'San Fernando',
'San Francisco',
'San Remigo',
'Santander',
'Sibonga',
'Sogod',
'Sta. Fe',
'Tabogon',
'Tabuelan',
'Talisay City',
'Toledo City',
'Tuburan',
'Tudela',
 'Compostela',
'Laac',
'Mabini',
'Maco',
'Maragusan',
'Mawab',
'Monkayo',
'Montevista',
'Nabunturan',
'New Bataan',
'Pantukan',
 'Alamada',
'Aleosan',
'Antipas',
'Arakan',
'Banisilan',
'Carmen',
'Kabacan',
'Kidapawan City',
'Libungan',
'Magpet',
'Makilala',
'Matalam',
'Midsayap',
"M'lang",
'Pigkawayan',
'Pikit',
'President Roxas',
'Tulunan',
 'Asuncion',
'Braulio E. Dujali',
'Carmen',
'Island Garden City Of Samal',
'Kapalong',
'New Corella',
'Panabo City',
'San Isidro',
'Sto. Tomas',
'Tagum City',
'Talaingod',
 'Bansalan',
'Davao City',
'Digos City',
'Don Marcelino',
'Hagonoy',
'Jose Abad Santos',
'Kiblawan',
'Magsaysay',
'Malalag',
'Malita',
'Matanao',
'Padada',
'Sarangani',
'Sta. Cruz',
'Sta. Maria',
'Sulop',
 'Baganga',
'Banaybanay',
'Boston',
'Caraga',
'Cateel',
'Gov. Generoso',
'Lupon',
'Manay',
'Mati',
'San Isidro',
'Tarragona',
 'Basilisa',
'Cagdianao',
'Dinagat',
'Libjo',
'Loreto',
'San Jose',
'Tubajon',
 'Arteche',
'Balangiga',
'Balangkayan',
'Borongan',
'Can-Avid',
'Dolores',
'Gen. Mac Arthur',
'Giporlos',
'Guiuan',
'Hernani',
'Hinabangan',
'Jipapad',
'Lawaan',
'Llorente',
'Maslog',
'Maydolong',
'Mercedes',
'Oras',
'Quinapondan',
'Salcedo',
'San Julian',
'San Policarpio',
'Sulat',
'Taft',
 'Buenavista',
'Jordan',
'Nueva Valencia',
'San Lorenzo',
'Sibunag',
 'Aguinaldo',
'Alfonso Lista',
'Asipulo',
'Banaue',
'Hingyon',
'Hungduan',
'Kiangan',
'Lagawe',
'Lamut',
'Mayoyao',
'Tinoc',
 'Adams',
'Bacarra',
'Badoc',
'Bangui',
'Banna (Espiritu)',
'Batac',
'Burgos',
'Carasi',
'Currimao',
'Dingras',
'Dumalneg',
'Laoag City',
'Marcos',
'Nueva Era',
'Pagudpud',
'Paoay',
'Pasuquin',
'Piddig',
'Pinili',
'San Nicolas',
'Sarrat',
'Solsona',
'Vintar',
 'Alilem',
'Banayoyo',
'Bantay',
'Burgos',
'Cabugao',
'Candon City',
'Caoayan',
'Cervantes',
'Galimuyod',
'Gregorio del Pilar',
'Lidlidda',
'Masingal',
'Nagbukel',
'Narvacan',
'Quirino (Angkaki)',
'Salcedo(Baugen)',
'San Emilio',
'San Esteban',
'San Ildefonso',
'San Juan (Lapog)',
'San Vicente',
'Santa',
'Santiago',
'Sigay',
'Sinait',
'Sta. Catalina',
'Sta. Cruz',
'Sta. Lucia',
'Sta. Maria',
'Sto. Domingo',
'Sugpon',
'Suyo',
'Tagudin',
'Vigan City',
 'Ajuy',
'Alimodian',
'Anilao',
'Badiangan',
'Balasan',
'Banate',
'Barotac Nuevo',
'Barotac Viejo',
'Batad',
'Bingawan',
'Cabatuan',
'Calinog',
'Carles',
'Concepcion',
'Dingle',
'Dueñas',
'Dumangas',
'Estancia',
'Guimbal',
'Igbaras',
'Iloilo City',
'Janiuay',
'Jaro',
'Lambunao',
'Leganes',
'Lemery',
'Leon',
'Maasin',
'Miag-Ao',
'Mina',
'New Lucena',
'Oton',
'Passi City',
'Pavia',
'Pototan',
'San Dionisio',
'San Enrique',
'San Joaquin',
'San Miguel',
'San Rafael',
'Sara',
'Sta. Barbara',
'Tigbauan',
'Tubungan',
'Zarraga',
 'Alicia',
'Angadanan',
'Aurora',
'Benito Soliven',
'Burgos',
'Cabagan',
'Cabatuan',
'Cauayan City',
'Cordon',
'Delfin Albano (Magsaysay)',
'Dinapigue',
'Divilican',
'Echague',
'Gamu',
'Ilagan',
'Jones',
'Luna',
'Maconacon',
'Mallig',
'Naguillan',
'Palanan',
'Quezon',
'Quirino',
'Ramon',
'Reina Mercedes',
'Roxas',
'San Agustin',
'San Guillermo',
'San Isidro',
'San Manuel',
'San Mariano',
'San Mateo',
'San Pablo',
'Santiago City',
'Sta. Maria',
'Sto. Tomas',
'Tumauini',
 'Balbalan',
'Lubuagan',
'Pasil',
'Pinukpuk',
'Rizal',
'Tabuk',
'Tanudan',
'Tinglayan',
 'Agoo',
'Aringay',
'Bacnotan',
'Bagulin',
'Balaoan',
'Bangar',
'Bauang',
'Burgos',
'Caba',
'Luna',
'Naguilian',
'Pugo',
'Rosario',
'San Fernando City',
'San Gabriel',
'San Juan',
'Santol',
'Sto. Tomas',
'Sudipen',
'Tubao',
 'Alaminos',
'Bay',
'Biñan',
'Cabuyao',
'Calamba City',
'Calauan',
'Cavinti',
'Famy',
'Kalayaan',
'Liliw',
'Los Baños',
'Luisiana',
'Lumban',
'Mabitac',
'Magdalena',
'Majayjay',
'Nagcarlan',
'Paete',
'Pagsanjan',
'Pakil',
'Pangil',
'Pila',
'Rizal',
'San Pablo City',
'San Pedro',
'Siniloan',
'Sta. Cruz',
'Sta. Maria',
'Sta. Rosa',
'Victoria',
 'Bacolod',
'Baloi',
'Baroy',
'Dimaporo(Karomatan)',
'Iligan City',
'Kapatagan',
'Kauswagan',
'Kolambugan',
'Lala',
'Linamon',
'Magsaysay',
'Maigo',
'Matungao',
'Munai',
'Nunungan',
'Pantao Ragat',
'Pantar',
'Poona Piagapo',
'Salvador',
'Sapad',
'Sultan Naga Dimaporo',
'Tagoloan',
'Tangkal',
'Tubod',
 'Bacolod-Kalawi',
'Balabagan',
'Balindong',
'Bayang',
'Binidayan',
'Buadiposo-Buntong',
'Bubong',
'Bumbaran',
'Butig',
'Calanogas',
'Ditsaan-Ramain',
'Ganassi',
'Kapai',
'Kapatagan',
'Lumba-Bayabao',
'Lumbatan',
'Lumbayanague',
'Madalum',
'Madamba',
'Maguing',
'Malabang',
'Marantao',
'Marawi City',
'Marogong',
'Masiu',
'Mulondo',
'Pagayawan',
'Piagapo',
'Poona-Bayabao',
'Pualas',
'Saguiaran',
'Sultan Dumalondong',
'Sultan Gumander',
'Tagoloan',
'Tamparan',
'Taraka',
'Tubaran',
'Tugaya',
'Wao',
 'Abuyog',
'Alangalang',
'Albuera',
'Babatngon',
'Barugo',
'Bato',
'Baybay',
'Burauen',
'Calubian',
'Capoocan',
'Carigara',
'Dagami',
'Dulag',
'Hilongos',
'Hindang',
'Inopacan',
'Isabel',
'Jaro',
'Javier',
'Julita',
'Kananga',
'La Paz',
'Leyte',
'MacArthur',
'Mahaplag',
'Matag-ob',
'Matalom',
'Mayorga',
'Merida',
'Ormoc City',
'Palo',
'Palompon',
'Pastrana',
'San Isidro',
'San Miguel',
'Santa Fe',
'Tabango',
'Tabontabon',
'Tacloban City',
'Tanauan',
'Tolosa',
'Tunga',
'Villaba',
 'Ampatuan',
'Barira',
'Buldon',
'Buluan',
'Cotabato City',
'Datu Odin Sinsuat',
'Datu Paglas',
'Datu Piang',
'Gen. Salipada K. Pendatun',
'Kabuntalan',
'Mamasapano',
'Matanog',
'Pagagawan',
'Pagalungan',
'Paglat',
'Parang',
'Shariff Aguak',
'South Upi',
'Sultan Kudarat',
'Sultan Mastura',
'Sultan Sa Barongis',
'Talayan',
'Talitay',
'Upi',
 'Boac',
'Buenavista',
'Gasan',
'Mogpog',
'Sta. Cruz',
'Torrijos',
 'Aroroy',
'Baleno',
'Balud',
'Batuan',
'Cataingan',
'Cawayan',
'Claveria',
'Dimasalang',
'Esperanza',
'Mandaon',
'Masbate City',
'Milagros',
'Mobo',
'Monreal',
'Palanas',
'Pio V. Corpuz',
'Placer',
'San Fernando',
'San Jacinto',
'San Pascual',
'Uson',
 'Caloocan City',
'Las Piñas City',
'Makati City',
'Malabon City',
'Mandaluyong City',
'Manila',
'Marikina City',
'Muntinlupa City',
'Navotas',
'Parañaque City',
'Pasay City',
'Pasig City',
'Pateros',
'Quezon City',
'San Juan City',
'Taguig City',
'Valenzuela City',
 'Aloran',
'Baliangao',
'Bonifacio',
'Calamba',
'Clarin',
'Concepcion',
'Don Victoriano Chiongbian',
'Jimenez',
'Lopez Jaena',
'Oroquieta City',
'Ozamis City',
'Panaon',
'Plaridel',
'Sapang Dalaga',
'Sinacaban',
'Tangub City',
'Tudela',
 'Alubijid',
'Balingasag',
'Balingoan',
'Binuangan',
'Cagayan De Oro City',
'Claveria',
'El Salvador',
'Gingoog City',
'Gitagum',
'Initao',
'Jasaan',
'Kinoguitan',
'Lagonglong',
'Laguindingan',
'Libertad',
'Lugait',
'Magsaysay',
'Manticao',
'Medina',
'Naawan',
'Opol',
'Salay',
'Sugbongcogon',
'Tagoloan',
'Talisayan',
'Villanueva',
 'Barlig',
'Bauko',
'Besao',
'Bontoc',
'Natonin',
'Paracelis',
'Sabangan',
'Sadanga',
'Sagada',
'Tadian',
 'Bacolod City',
'Bago City',
'Binalbagan',
'Cadiz City',
'Calatrava',
'Candoni',
'Cauayan',
'Enrique B. Magalona',
'Escalante City',
'Himamaylan City',
'Hinigaran',
'Hinoba-An',
'Ilog',
'Isabela',
'Kabankalan City',
'La Carlota City',
'La Castellana',
'Manapla',
'Moises Padilla',
'Murcia',
'Pontevedra',
'Pulupandan',
'Sagay City',
'Salvador Benedicto',
'San Carlos City',
'San Enrique',
'Silay City',
'Sipalay City',
'Talisay City',
'Toboso',
'Valladolid',
'Victorias City',
 'Amlan',
'Ayungon',
'Bacong',
'Bais City',
'Basay',
'Bayawan City',
'Bindoy (Payabon)',
'Canlaon City',
'Dauin',
'Dumaguete City',
'Guihulngan',
'Jimalalud',
'La Libertad',
'Mabinay',
'Manjuyod',
'Pamplona',
'San Jose',
'Siaton',
'Sibulan',
'Sta. Catalina',
'Tanjay City',
'Tayasan',
'Valencia',
'Vallahermosa',
'Zamboanguita',
 'Allen',
'Biri',
'Bobon',
'Capul',
'Catarman',
'Catubig',
'Gamay',
'Laoang',
'Lapinig',
'Las Navas',
'Lavezares',
'Lope de Vega',
'Mapanas',
'Mondragon',
'Palapag',
'Pambujan',
'Rosario',
'San Antonio',
'San Isidro',
'San Jose',
'San Roque',
'San Vicente',
'Silvino Lobos',
'Victoria',
 'Aliaga',
'Bongabon',
'Cabanatuan City',
'Cabiao',
'Carranglan',
'Cuyapo',
'Gabaldon',
'Gapan City',
'Gen. Mamerto Natividad',
'Gen. Tinio',
'Guimba',
'Jaen',
'Laur',
'Licab',
'Llanera',
'Lupao',
'Nampicuan',
'Palayan City',
'Pantabangan',
'Peñaranda',
'Quezon',
'Rizal',
'San Antonio',
'San Isidro',
'San Jose City',
'San Leonardo',
'Science City of Muñoz',
'Sta. Rosa',
'Sto. Domingo',
'Talavera',
'Talugtug',
'Zaragosa',
 'Alfonso Castañeda',
'Ambaguio',
'Aritao',
'Bagabag',
'Bambang',
'Bayombong',
'Diadi',
'Dupax Del Norte',
'Dupax Del Sur',
'Kasibu',
'Kayapa',
'Quezon',
'Solano',
'Sta. Fe',
'Villaverde',
 'Abra De Ilog',
'Calintaan',
'Looc',
'Lubang',
'Magsaysay',
'Mamburao',
'Paluan',
'Rizal',
'Sablayan',
'San Jose',
'Sta. Cruz',
 'Baco',
'Bansud',
'Bongabong',
'Bulalacao',
'Calapan City',
'Gloria',
'Mansalay',
'Naujan',
'Pinamalayan',
'Pola',
'Puerto Galera',
'Roxas',
'San Teodoro',
'Socorro',
'Victoria',
 'Agutaya',
'Araceli',
'Balabac',
'Bataraza',
"Brooke'S Point",
'Busuanga',
'Cagayancillo',
'Coron',
'Culion',
'Cuyo',
'Dumaran',
'El Nido',
'Kalayaan',
'Linapacan',
'Magsaysay',
'Narra',
'Puerto Princesa City',
'Quezon',
'Rizal',
'Roxas',
'San Vicente',
'Sofronio Española',
'Taytay',
'Aborlan',
 'Angeles City',
'Apalit',
'Arayat',
'Bacolor',
'Candaba',
'Floridablanca',
'Guagua',
'Lubao',
'Mabalacat',
'Macabebe',
'Magalang',
'Masantol',
'Mexico',
'Minalin',
'Porac',
'San Fernando City',
'San Luis',
'San Simon',
'Sasmuan',
'Sta. Ana',
'Sta. Rita',
'Sto. Tomas',
 'Agno',
'Aguilar',
'Alaminos City',
'Alcala',
'Anda',
'Asingan',
'Balungao',
'Bani',
'Basista',
'Bautista',
'Bayambang',
'Binalonan',
'Binmaley',
'Bolinao',
'Bugallon',
'Burgos',
'Calasiao',
'Dagupan City',
'Dasol',
'Infanta',
'Labrador',
'Laoac',
'Lingayen',
'Mabini',
'Malasiqui',
'Manaoag',
'Mangaldan',
'Mangatarem',
'Mapandan',
'Natividad',
'Pozorrubio',
'Rosales',
'San Carlos City',
'San Fabian',
'San Jacinto',
'San Manuel',
'San Nicolas',
'San Quintin',
'Sison',
'Sta. Barbara',
'Sta. Maria',
'Sto. Tomas',
'Sual',
'Tayug',
'Umingan',
'Urbiztondo',
'Urdaneta City',
'Villasis',
 'Agdangan',
'Alabat',
'Atimonan',
'Buenavista',
'Burdeos',
'Calauag',
'Candelaria',
'Catanauan',
'Dolores',
'Gen. Luna',
'Gen. Nakar',
'Guinayangan',
'Gumaca',
'Infanta',
'Jomalig',
'Lopez',
'Lucban',
'Lucena City',
'Macalelon',
'Mauban',
'Mulanay',
'Padre Burgos',
'Pagbilao',
'Panukulan',
'Patnanungan',
'Perez',
'Pitogo',
'Plaridel',
'Polillo',
'Quezon',
'Real',
'Sampaloc',
'San Andres',
'San Antonio',
'San Francisco',
'San Narciso',
'Sariaya',
'Tagkawayan',
'Tayabas',
'Tiaong',
'Unisan',
 'Aglipay',
'Cabarroguis',
'Diffun',
'Maddela',
'Nagtipunan',
'Saguday',
 'Angono',
'Antipolo City',
'Baras',
'Binangonan',
'Cainta',
'Cardona',
'Jala-Jala',
'Morong',
'Pililia',
'Rodriguez (Montalban)',
'San Mateo',
'Tanay',
'Taytay',
'Teresa',
 'Alcantara',
'Banton',
'Cajidiocan',
'Calatrava',
'Concepcion',
'Corcuera',
'Ferrol',
'Looc',
'Magdiwang',
'Odiongan',
'Romblon',
'San Agustin',
'San Andres',
'San Fernando',
'San Jose',
'Santa Fe',
'Santa Maria',
 'Almagro',
'Basey',
'Calbayog City',
'Calbiga',
'Catbalogan',
'Daram',
'Gandara',
'Hinabangan',
'Jiabong',
'Marabut',
'Matuguinao',
'Motiong',
'Pangsanghan',
'Paranas (Wright)',
'Pinabacdao',
'San Jorge',
'San Jose De Buan',
'San Sebastian',
'Sta. Margarita',
'Sta. Rita',
'Sto. Niño',
'Tagapul-an',
'Talalora',
'Tarangan',
'Villareal',
'Zumarraga',
 'Alabel',
'Glan',
'Kiamba',
'Maasim',
'Maitum',
'Malapatan',
'Malungon',
 'Enrique  Villanueva',
'Larena',
'Lazi',
'Maria',
'San Juan',
'Siquijor',
 'Barcelona',
'Bulan',
'Bulusan',
'Casiguran',
'Castilla',
'Donsol',
'Gubat',
'Irosin',
'Juban',
'Magallanes',
'Matnog',
'Pilar',
'Prieto Diaz',
'Sorsogon City',
'Sta. Magdalena',
 'Banga',
'Gen. Santos City',
'Koronadal City',
'Lake Sebu',
'Norala',
'Polomolok',
'Sto. Niño',
'Surallah',
'Tampakan',
'Tantangan',
"T'Boli",
'Tupi',
 'Anahawan',
'Bontoc',
'Hinunangan',
'Hinundayan',
'Libagon',
'Liloan',
'Limasawa',
'Maasin City',
'Macrohon',
'Malitbog',
'Padre Burgos',
'Pintuyan',
'Saint Bernard',
'San Francisco',
'San Juan',
'San Ricardo',
'Silago',
'Sogod',
'Tomas Oppus',
 'Bagumbayan',
'Columbio',
'Esperanza',
'Isulan',
'Kalamansig',
'Lambayong',
'Lebak',
'Lutayan',
'Palimbang',
'Pres. Quirino',
'Sen. Ninoy S. Aquino',
'Tacurong City',
 'Hadji Panglima Tahil',
'Indanan',
'Jolo',
'Kalingalan Calauang',
'Lugus',
'Luuk',
'Maimbung',
'Old Panamao',
'Pandami',
'Panglima Estino',
'Pangutaran',
'Parang',
'Pata',
'Patikul',
'Siasi',
'Tapul',
'Tongkil',
 'Alegria',
'Bacuag',
'Basilisa',
'Burgos',
'Cagdianao',
'Claver',
'Dapa',
'Del Carmen',
'Dinagat',
'General Luna',
'Gigacuit',
'Libjo',
'Loreto',
'Mainit',
'Malimono',
'Pilar',
'Placer',
'San Benito',
'San Francisco',
'San Isidro',
'San Jose',
'Sison',
'Socorro',
'Sta. Monica',
'Surigao City',
'Tagana-An',
'Tubajon',
'Tubod',
 'Barobo',
'Bayabas',
'Bislig City',
'Cagwait',
'Cantilan',
'Carmen',
'Carrascal',
'Cortes',
'Hinatuan',
'Lanuza',
'Lianga',
'Lingig',
'Madrid',
'Marihatag',
'San Agustin',
'San Miguel',
'Tagbina',
'Tago',
'Tandag',
 'Anao',
'Bamban',
'Camiling',
'Capas',
'Concepcion',
'Gerona',
'La Paz',
'Mayantoc',
'Moncada',
'Paniqui',
'Pura',
'Ramos',
'San Clemente',
'San Jose',
'San Manuel',
'Sta. Ignacia',
'Tarlac City',
'Victoria',
 'Bongao',
'Languyan',
'Mapun',
'Panglima Sugala',
'Sapa-Sapa',
'Simunul',
'Sitangkai',
'South Ubian',
'Tandubas',
'Turtle Islands',
 'Botolan',
'Cabangan',
'Candelaria',
'Castillejos',
'Iba',
'Masinloc',
'Olongapo City',
'Palauig',
'San Antonio',
'San Felipe',
'San Marcelino',
'San Narciso',
'Sta. Cruz',
'Subic',
 'Bacungan (Leon B. Postigo)',
'Baliguian',
'Dapitan City',
'Dipolog City',
'Godod',
'Gutalac',
'Jose Dalman',
'Kalawit',
'Katipunan',
'La Libertad',
'Labason',
'Liloy',
'Manukan',
'Mutia',
'Piñan',
'Polanco',
'Pres.Manuel Roxas',
'Rizal',
'Salug',
'Sergio Osmeña, Sr.',
'Siayan',
'Sibuco',
'Sibutad',
'Sindangan',
'Siocon',
'Sirawai',
'Tampilisan',
 'Aurora',
'Bayog',
'Dimataling',
'Dinas',
'Dumalinao',
'Dumingag',
'Guipos',
'Josefina',
'Kumalarang',
'Labangan',
'Lakewood',
'Lapuyan',
'Mahayag',
'Margosatubig',
'Midsalip',
'Molave',
'Pagadian City',
'Pitogo',
'Ramon Magsaysay',
'San Miguel',
'San Pablo',
'Sominot',
'Tabina',
'Tambulig',
'Tigbao',
'Tukuran',
'Vincenzo A. Sagun',
'Zamboanga City',
 'Alicia',
'Buug',
'Diplahan',
'Imelda',
'Ipil',
'Kabasalan',
'Mabuhay',
'Malangas',
'Naga',
'Olutanga',
'Payao',
'Roseller T. Lim',
'Siay',
'Talusan',
'Titay',
'Tungawan'
		);	
	}

public function getSexatIndex($index){
		$array = $this->getSex();
		return $array[$index];
	}

public function getClassificationatIndex($index){
		$array = $this->getClassifications();
		return $array[$index];
	}

public function getCategoryatIndex($index){
		$array = $this->getCategories();
		return $array[$index];
	}
	
public function getOrganizationFormatIndex($index){
		$array = $this->getOrganizationForms();
		return $array[$index];
	}
	
public function getOrganizationTypeatIndex($index){
		$array = $this->getOrganizationTypes();
		return $array[$index];
	}
	
public function getBusinessCategoryatIndex($index){
		$array = $this->getBusinessCategories();
		return $array[$index];
	}
	
public function getCountryatIndex($index){
		$array = $this->getCountries();
		return $array[$index];
	}
	
public function getRegionatIndex($index){
		$array = $this->getRegions();
		return $array[$index];
	}
	
public function getProvinceatIndex($index){
		$array = $this->getProvinces();
		return $array[$index];
	}
	
public function getCityorMunicipalityatIndex($index){
		$array = $this->getCitiesorMunicipalities();
		return $array[$index];
	}
	
public function findIndex($array,$string){
	for($i=0;$i<count($array);$i++){
			if($array[$i]==$string){	
				return $i;
			}	
		}
	return 0;
}

public function getSexIndex($string){
		$array = $this->getSex();
		return $this->findIndex($array,$string);
	}
	
public function getClassificationIndex($string){
		$array = $this->getClassifications();
		return $this->findIndex($array,$string);
	}
	
public function getCategoryIndex($string){
		$array = $this->getCategories();
		return $this->findIndex($array,$string);
	}
	
public function getOrganizationFormIndex($string){
		$array = $this->getOrganizationForms();
		return $this->findIndex($array,$string);
	}
	
public function getOrganizationTypeIndex($string){
		$array = $this->getOrganizationTypes();
		return $this->findIndex($array,$string);
	}
	
public function getBusinessCategoryIndex($string){
		$array = $this->getBusinessCategories();
		return $this->findIndex($array,$string);
	}
	
	
public function getCountryIndex($country){
		$array = $this->getCountries();
		return $this->findIndex($array,$country);
	}
	
public function getRegionIndex($region){
		$array = $this->getRegions();
		return $this->findIndex($array,$region);
	}
	
public function getProvinceIndex($province){
		$array = $this->getProvinces();
		return $this->findIndex($array,$province);
	}
	
public function getCityorMunicipalityIndex($c){
		$array = $this->getCitiesorMunicipalities();
		return $this->findIndex($array,$c);
	}
}